### ISSUE TITLE
secretKey 를 가져오지 못하는 문제 보고 드려요..

### ISSUE THREAD

**Issue by touguy** [sejoung/tomcat-jdbc-encrypt#2]
올려주신 내용 너무 유용하게 잘쓰고 있습니다 ^^

RHEL 7.4 64 bit
tomcat 7.0 상에서 사용중입니다.
소스 변경 해서 로그로 찍어보니 secretKey 를  아무리 해도 못가져오는데... 
null 로 찍히네요...

일단 소스 내부에서  직접 스트링으로 지정 해서 회피하긴 했는데...
혹시 제 환경에서만 문제일까요?

**Comment by Evenoah** [comment]
저도 같은 문제가 발생하네요;

**Comment by sejoung** [comment]
아 감사합니다 오늘에서야 해당 건을 확인 했네요 해당 부분 코드를 수정했습니다. 제보 감사합니다.
